// ============================================================
// config.js — Developer Controls, Data Sources & Constants
// ============================================================

// DEVELOPER CONTROL:
// true  = Force "She Said Yes" state (Stamp & Content visible)
// false = Force "Initial" state (Yes/No Buttons visible)
// null  = Use Browser Memory (Normal User Experience)
const SHOW_ACCEPTED_VIEW = null;

// Toggle individual memory cards on/off
const MEMORY_CONTROLS = {
    memory1: true,
    memory2: true,
    memory3: true,
    memory4: true,
    memory5: true,
    memory6: true,
    memory7: true,
    memory8: true,
    memory9: true,
    memory10: true,
    memory11: true,
    memory12: true,
    memory13: true,
};

// Gallery image filenames (relative to Assets/Gallery/)
const GALLERY_IMAGES = [
    'IMG-20260117-WA0011.jpg', 'IMG-20260117-WA0013.jpg', 'IMG-20260117-WA0014.jpg',
    'IMG-20260117-WA0015.jpg', 'IMG-20260118-WA0035.jpg', 'IMG-20260118-WA0037.jpg',
    'IMG-20260119-WA0012.jpg', 'IMG-20260119-WA0015.jpg', 'IMG-20260119-WA0022.jpg',
    'IMG-20260119-WA0023.jpg', 'IMG20250604200831~2.jpg', 'IMG20250605105032.jpg',
    'IMG20250605105038.jpg', 'IMG20251130160325~2.jpg', 'IMG20251130171445~2.jpg',
    'IMG20251230172446.jpg',
];

// Music playlist
const PLAYLIST = [
    { title: "Sang Rahiyo \ud83e\udef6", artist: "Jasleen Royal, Ujjwal Kashyap", src: "Assets/Songs/Sang Rahiyo\ud83e\udef6.webm", art: "Assets/Images/website_icon.png" },
    { title: "Aankhon mein teri \u2728", artist: "K.K.", src: "Assets/Songs/Aankhon mein teri.webm", art: "Assets/Images/website_icon.png" },
    { title: "10,000 Hours \ud83d\udd52", artist: "Dan + Shay, Justin Bieber", src: "Assets/Songs/10,000 Hours.webm", art: "Assets/Images/website_icon.png" },
    { title: "Agar Tum Saath Ho \ud83e\udde1", artist: "Alka Yagnik, Arijit Singh", src: "Assets/Songs/Agar Tum Saath Ho.webm", art: "Assets/Images/website_icon.png" },
    { title: "A Thousand Years \u23f3", artist: "Christina Perri", src: "Assets/Songs/A Thousand Years.webm", art: "Assets/Images/website_icon.png" },
    { title: "Ajj Din Chadeya \u2600\ufe0f", artist: "Rahat Fateh Ali Khan", src: "Assets/Songs/Ajj Din Chadeya.webm", art: "Assets/Images/website_icon.png" },
    { title: "All of Me \ud83c\udfb9", artist: "John Legend", src: "Assets/Songs/All of Me.webm", art: "Assets/Images/website_icon.png" },
    { title: "Always Remember Us this Way \ud83d\udcab", artist: "Lady Gaga", src: "Assets/Songs/Always Remember Us this Way.webm", art: "Assets/Images/website_icon.png" },
    { title: "Beautiful In White \ud83e\udd0d", artist: "Shane Filan", src: "Assets/Songs/Beautiful In White.webm", art: "Assets/Images/website_icon.png" },
    { title: "Apna Bana Le Piya \ud83d\udc95", artist: "Arijit Singh", src: "Assets/Songs/Apna Bana Le Piya.webm", art: "Assets/Images/website_icon.png" },
    { title: "Can't Help Falling In Love With You \ud83c\udf39", artist: "Elvis Presley", src: "Assets/Songs/Can't Help Falling In Love With You.webm", art: "Assets/Images/website_icon.png" },
    { title: "Bakhuda Tumhi Ho \ud83d\ude4f", artist: "Atif Aslam, Alka Yagnik", src: "Assets/Songs/BakhudaTumHiHo.webm", art: "Assets/Images/website_icon.png" },
    { title: "Die With A Smile \ud83d\ude0a", artist: "Lady Gaga, Bruno Mars", src: "Assets/Songs/Die With A Smile.webm", art: "Assets/Images/website_icon.png" },
    { title: "Be Intehaan \ud83c\udf19", artist: "Sunidhi Chauhan, Atif Aslam", src: "Assets/Songs/BeIntehan.webm", art: "Assets/Images/website_icon.png" },
    { title: "Don't Give Up On Me \ud83d\udcaa", artist: "Andy Grammer", src: "Assets/Songs/Don't Give Up On Me.webm", art: "Assets/Images/website_icon.png" },
    { title: "Bheegi Si Bhaagi Si \u2614", artist: "Mohit Chauhan, Antara Mitra", src: "Assets/Songs/BheegiSiBhaagiSi.webm", art: "Assets/Images/website_icon.png" },
    { title: "Everything I Do I Do It For You \ud83d\udc98", artist: "Bryan Adams", src: "Assets/Songs/Everything I Do I Do It For You.webm", art: "Assets/Images/website_icon.png" },
    { title: "Chahun Main Ya Naa \ud83d\udcad", artist: "Arijit Singh", src: "Assets/Songs/ChahunMainYaNaa.webm", art: "Assets/Images/website_icon.png" },
    { title: "Gone Gone Gone \ud83c\udfb8", artist: "Phillip Phillips", src: "Assets/Songs/Gone Gone Gone.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dandelions \ud83c\udf3c", artist: "Ruth B.", src: "Assets/Songs/Dandelions\ud83c\udf3c.webm", art: "Assets/Images/website_icon.png" },
    { title: "Hero \ud83e\uddb8", artist: "Enrique Iglesias", src: "Assets/Songs/Hero.webm", art: "Assets/Images/website_icon.png" },
    { title: "Darasal \u2728", artist: "Atif Aslam", src: "Assets/Songs/Darasal.webm", art: "Assets/Images/website_icon.png" },
    { title: "I Don't Wanna Live Forever \u267e\ufe0f", artist: "Zayn, Taylor Swift", src: "Assets/Songs/I Don't Wanna Live Forever.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dariya \ud83c\udf0a", artist: "Arko", src: "Assets/Songs/Dariya.webm", art: "Assets/Images/website_icon.png" },
    { title: "I Think They Call This Love \ud83d\udc97", artist: "Elliot James Reay", src: "Assets/Songs/I Think They Call This Love.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dekha Hazaron Dafa Apko \ud83d\udc40", artist: "Arijit Singh, Palak Muchhal", src: "Assets/Songs/Dekha Hazaron Dafa Apko.webm", art: "Assets/Images/website_icon.png" },
    { title: "I Won't Give Up \ud83d\udd25", artist: "Jason Mraz", src: "Assets/Songs/I Won't Give Up.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dil Kyun Yeh Mera Shor Kare \ud83d\udc93", artist: "K.K.", src: "Assets/Songs/DilKyunYehMeraShorKare.webm", art: "Assets/Images/website_icon.png" },
    { title: "I'm Your's \u2600\ufe0f", artist: "Jason Mraz", src: "Assets/Songs/I'm Your's.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dil Mein Ho Tum \ud83d\udc9c", artist: "Armaan Malik, Bappi Lahiri", src: "Assets/Songs/Dil Mein Ho Tum.webm", art: "Assets/Images/website_icon.png" },
    { title: "Iris \ud83c\udf1f", artist: "Goo Goo Dolls", src: "Assets/Songs/Iris.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dooriyan \ud83d\udeb6", artist: "Mohit Chauhan", src: "Assets/Songs/Dooriyan.webm", art: "Assets/Images/website_icon.png" },
    { title: "La Vei En Rose \ud83c\udf39", artist: "\u00c9dith Piaf", src: "Assets/Songs/La Vei En Rose.webm", art: "Assets/Images/website_icon.png" },
    { title: "Dooron Dooron \ud83c\udf0c", artist: "Paresh Pahuja, Shiv Tandan", src: "Assets/Songs/Dooron Dooron.webm", art: "Assets/Images/website_icon.png" },
    { title: "Love Me Like You Do \ud83d\udc8b", artist: "Ellie Goulding", src: "Assets/Songs/Love Me Like You Do.webm", art: "Assets/Images/website_icon.png" },
    { title: "Ek Din Aap \ud83c\udf05", artist: "Kumar Sanu, Alka Yagnik", src: "Assets/Songs/Ek Din Aap.webm", art: "Assets/Images/website_icon.png" },
    { title: "Love Me Thoda Aur \ud83d\udc9e", artist: "Arijit Singh", src: "Assets/Songs/LoveMeThodaAur.webm", art: "Assets/Images/website_icon.png" },
    { title: "Ek Ladki Ko Dekha Tho \ud83d\ude0d", artist: "Kumar Sanu", src: "Assets/Songs/Ek Ladki Ko Dekha Tho.webm", art: "Assets/Images/website_icon.png" },
    { title: "Love You Till The End \ud83d\udc9d", artist: "The Pogues", src: "Assets/Songs/Love You Till The End.webm", art: "Assets/Images/website_icon.png" },
    { title: "Enna Sona \ud83e\udd70", artist: "Arijit Singh", src: "Assets/Songs/Enna Sona.webm", art: "Assets/Images/website_icon.png" },
    { title: "Main Hoon Hero Tera \ud83e\uddb8\u200d\u2642\ufe0f", artist: "Armaan Malik", src: "Assets/Songs/Main Hoon Hero Tera.webm", art: "Assets/Images/website_icon.png" },
    { title: "Hawayein \ud83c\udf43", artist: "Arijit Singh", src: "Assets/Songs/Hawayein.webm", art: "Assets/Images/website_icon.png" },
    { title: "Make You Mine \ud83d\udc8e", artist: "PUBLIC", src: "Assets/Songs/Make You Mine.webm", art: "Assets/Images/website_icon.png" },
    { title: "Hosanna \ud83d\ude4c", artist: "Leon D'Souza, Suzanne D'Mello", src: "Assets/Songs/Hosanna.webm", art: "Assets/Images/website_icon.png" },
    { title: "My Heart Will Go On \ud83d\udea2", artist: "Celine Dion", src: "Assets/Songs/My Heart Will Go On.webm", art: "Assets/Images/website_icon.png" },
    { title: "Hum Tum \ud83d\udc6b", artist: "Alka Yagnik, Babul Supriyo", src: "Assets/Songs/Hum Tum.webm", art: "Assets/Images/website_icon.png" },
    { title: "My Love \ud83d\udc99", artist: "Westlife", src: "Assets/Songs/My Love.webm", art: "Assets/Images/website_icon.png" },
    { title: "Jaan Ban Gaye \ud83e\udef6", artist: "Vishal Mishra, Asees Kaur", src: "Assets/Songs/Jaan Ban Gaye.webm", art: "Assets/Images/website_icon.png" },
    { title: "Night Changes \ud83c\udf19", artist: "One Direction", src: "Assets/Songs/Night Changes.webm", art: "Assets/Images/website_icon.png" },
    { title: "Janam Janam \u267e\ufe0f", artist: "Arijit Singh, Antara Mitra", src: "Assets/Songs/Janam Janam.webm", art: "Assets/Images/website_icon.png" },
    { title: "Nothings Gonna Change My Love for You \ud83d\udc96", artist: "George Benson", src: "Assets/Songs/Nothings Gonna Change My Love for You.webm", art: "Assets/Images/website_icon.png" },
    { title: "Jeene Laga Hoon \ud83c\udf1e", artist: "Atif Aslam, Shreya Ghoshal", src: "Assets/Songs/Jeene Laga Hoon.webm", art: "Assets/Images/website_icon.png" },
    { title: "Perfect \ud83d\udc8d", artist: "Ed Sheeran", src: "Assets/Songs/Perfect.webm", art: "Assets/Images/website_icon.png" },
    { title: "Kaise Hua \ud83e\udee0", artist: "Vishal Mishra", src: "Assets/Songs/Kaise Hua.webm", art: "Assets/Images/website_icon.png" },
    { title: "Photograph \ud83d\udcf8", artist: "Ed Sheeran", src: "Assets/Songs/Photograph.webm", art: "Assets/Images/website_icon.png" },
    { title: "Kho Gaye Hum Kahan \ud83c\udf0c", artist: "Jasleen Royal, Prateek Kuhad", src: "Assets/Songs/KhoGayeHumKahan.webm", art: "Assets/Images/website_icon.png" },
    { title: "Rewrite The Stars \u2b50", artist: "Zac Efron, Zendaya", src: "Assets/Songs/Rewrite The Stars.webm", art: "Assets/Images/website_icon.png" },
    { title: "Kinna Sonna \ud83c\udf3a", artist: "Jubin Nautiyal, Dhvani Bhanushali", src: "Assets/Songs/Kinna Sonna.webm", art: "Assets/Images/website_icon.png" },
    { title: "Say You Won't Let Go \ud83e\udee8", artist: "James Arthur", src: "Assets/Songs/Say You Won't Let Go.webm", art: "Assets/Images/website_icon.png" },
    { title: "Lae Dooba \ud83c\udf0a", artist: "Arijit Singh", src: "Assets/Songs/LaeDooba.webm", art: "Assets/Images/website_icon.png" },
    { title: "Senorita \ud83d\udc83", artist: "Shawn Mendes, Camila Cabello", src: "Assets/Songs/Senorita.webm", art: "Assets/Images/website_icon.png" },
    { title: "Lover \ud83e\udd0d", artist: "Taylor Swift", src: "Assets/Songs/Lover.webm", art: "Assets/Images/website_icon.png" },
    { title: "Shallow \ud83c\udf0a", artist: "Lady Gaga, Bradley Cooper", src: "Assets/Songs/Shallow.webm", art: "Assets/Images/website_icon.png" },
    { title: "Main Tenu Samjhawan \ud83c\udfb6", artist: "Arijit Singh, Shreya Ghoshal", src: "Assets/Songs/MainTenuSamjhanwa.webm", art: "Assets/Images/website_icon.png" },
    { title: "She \ud83c\udf37", artist: "Elvis Costello", src: "Assets/Songs/She.webm", art: "Assets/Images/website_icon.png" },
    { title: "Maiya Menu \ud83d\ude07", artist: "Sachet Tandon", src: "Assets/Songs/Maiya Menu.webm", art: "Assets/Images/website_icon.png" },
    { title: "Somebody's Me \ud83d\udc94", artist: "Enrique Iglesias", src: "Assets/Songs/Somebody's Me.webm", art: "Assets/Images/website_icon.png" },
    { title: "Mera Pehla Pehla Pyaar \ud83d\udc9d", artist: "K.K.", src: "Assets/Songs/MeraPehlaPehlaPyaar.webm", art: "Assets/Images/website_icon.png" },
    { title: "Somewhere Only We Know \ud83c\udf3f", artist: "Keane", src: "Assets/Songs/Somewhere Only We Know.webm", art: "Assets/Images/website_icon.png" },
    { title: "Nazm Nazm \ud83d\udcdc", artist: "Arko", src: "Assets/Songs/NazmNazm.webm", art: "Assets/Images/website_icon.png" },
    { title: "Te Amo \ud83c\udf39", artist: "Ash King", src: "Assets/Songs/TeAmo.webm", art: "Assets/Images/website_icon.png" },
    { title: "Nenjukulle \ud83c\udfb6", artist: "Shakthisree Gopalan, A.R. Rahman", src: "Assets/Songs/Nenjukulle.webm", art: "Assets/Images/website_icon.png" },
    { title: "The Night We Met \ud83c\udf11", artist: "Lord Huron", src: "Assets/Songs/The Night We Met.webm", art: "Assets/Images/website_icon.png" },
    { title: "Pal \u231b", artist: "Arijit Singh, Shreya Ghoshal", src: "Assets/Songs/Pal.webm", art: "Assets/Images/website_icon.png" },
    { title: "Thinking Out Loud \ud83d\udcad", artist: "Ed Sheeran", src: "Assets/Songs/Thinking Out Loud.webm", art: "Assets/Images/website_icon.png" },
    { title: "Pal Pal Dil Ke Paas \ud83d\udc93", artist: "Kishore Kumar", src: "Assets/Songs/Pal Pal Dil Ke Paas.webm", art: "Assets/Images/website_icon.png" },
    { title: "Until I Found You \ud83d\udd0d", artist: "Stephen Sanchez", src: "Assets/Songs/Until I Found You.webm", art: "Assets/Images/website_icon.png" },
    { title: "Pehli Nazar Mein \ud83d\udc40", artist: "Atif Aslam", src: "Assets/Songs/PehliNazarMein.webm", art: "Assets/Images/website_icon.png" },
    { title: "When You Say Nothing At All \ud83e\udd10", artist: "Ronan Keating", src: "Assets/Songs/When You Say Nothing At All.webm", art: "Assets/Images/website_icon.png" },
    { title: "Raabta \ud83d\udd17", artist: "Arijit Singh", src: "Assets/Songs/Raabta.webm", art: "Assets/Images/website_icon.png" },
    { title: "You're Beautiful \ud83c\udf1f", artist: "James Blunt", src: "Assets/Songs/You're Beautiful.webm", art: "Assets/Images/website_icon.png" },
    { title: "Raataan Lambiyan \ud83c\udf19", artist: "Jubin Nautiyal, Asees Kaur", src: "Assets/Songs/Raataan Lambiyan.webm", art: "Assets/Images/website_icon.png" },
    { title: "You're Still The One \ud83d\udc91", artist: "Shania Twain", src: "Assets/Songs/You're Still The One.webm", art: "Assets/Images/website_icon.png" },
    { title: "Rabba Mein Tho Maar Gaya Oye \ud83d\ude4f", artist: "Rahat Fateh Ali Khan", src: "Assets/Songs/Rabba Mein Tho Maar Gaya Oye.webm", art: "Assets/Images/website_icon.png" },
    { title: "Sajde \ud83e\udee1", artist: "Arijit Singh", src: "Assets/Songs/Sajde.webm", art: "Assets/Images/website_icon.png" },
    { title: "Shukran Allah \ud83d\ude4f", artist: "Sonu Nigam, Shreya Ghoshal", src: "Assets/Songs/Shukran Allah.webm", art: "Assets/Images/website_icon.png" },
    { title: "Soniyo \ud83c\udf38", artist: "Shreya Ghoshal", src: "Assets/Songs/Soniyo.webm", art: "Assets/Images/website_icon.png" },
    { title: "Subhanallah \ud83c\udf1f", artist: "Sreeram, Shilpa Rao", src: "Assets/Songs/Subhanallah.webm", art: "Assets/Images/website_icon.png" },
    { title: "Sukoon Mila \ud83d\udd4a\ufe0f", artist: "Arijit Singh", src: "Assets/Songs/SukoonMila.webm", art: "Assets/Images/website_icon.png" },
    { title: "Suno Na Sangemarmar \ud83c\udfb5", artist: "Arijit Singh", src: "Assets/Songs/Suno Na Sangemarmar.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tera Ban Jaunga \ud83d\udc8d", artist: "Akhil", src: "Assets/Songs/TeraBanJaunga.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tera Chehra \ud83d\ude0d", artist: "Adnan Sami", src: "Assets/Songs/TeraChehra.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tera Hone Laga Hoon \ud83d\udc97", artist: "Atif Aslam, Alisha Chinai", src: "Assets/Songs/Tera Hone Laga Hoon.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tu Hain Toh \ud83c\udfb5", artist: "Pritam, Rahul Mishra", src: "Assets/Songs/TuHainTho.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tujhe Mein Rab Dikhta Hai \ud83d\ude07", artist: "Roop Kumar Rathod", src: "Assets/Songs/Tujhe Mein Rab Dikhta Hai.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tum Hi Ho \ud83d\udc96", artist: "Arijit Singh", src: "Assets/Songs/TumHiHo.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tum Mile \ud83c\udf08", artist: "Neeraj Shridhar", src: "Assets/Songs/TumMile.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tum Se Hi \ud83d\udc9e", artist: "Mohit Chauhan", src: "Assets/Songs/Tum Se Hi.webm", art: "Assets/Images/website_icon.png" },
    { title: "Tum Tak \ud83c\udf1e", artist: "A.R. Rahman, Javed Ali", src: "Assets/Songs/Tum Tak.webm", art: "Assets/Images/website_icon.png" },
    { title: "Vaaranam Aayiram \ud83c\udf3b", artist: "Harris Jayaraj", src: "Assets/Songs/Vaaranam Aayiram.webm", art: "Assets/Images/website_icon.png" },
];

// Shared constants
const DUCKED_VOLUME = 0.05;
const DEFAULT_VOLUME = 0.5;
const IDLE_DELAY = 10000; // Auto-scroll idle timeout (ms)
const ROSE_EMOJIS = ['\ud83c\udf39', '\ud83c\udf37', '\ud83d\udc90', '\ud83c\udf38'];
